// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PrBancoGuayaquilDb;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PrBancoGuayaquilDb
{
    public partial interface IPrBancoGuayaquilContextProcedures
    {
        Task<List<sp_consulta_personaResult>> sp_consulta_personaAsync(string i_CodicionBusqueda, string i_DatoBusqueda, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
