// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrBancoGuayaquilDb;

public partial class PbgUsuario
{
    public int Identificador { get; set; }

    public string Usuario { get; set; }

    public string Pass { get; set; }

    public DateTime? FechaCreacion { get; set; }
}