// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PrBancoGuayaquilDb;

public partial class PrBancoGuayaquilContext : DbContext
{
    public PrBancoGuayaquilContext(DbContextOptions<PrBancoGuayaquilContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PbgPersona> PbgPersona { get; set; }

    public virtual DbSet<PbgUsuario> PbgUsuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PbgPersona>(entity =>
        {
            entity.HasKey(e => e.Identificador)
                .HasName("Pk_Pbg_Persona")
                .IsClustered(false);

            entity.ToTable("Pbg_Persona");

            entity.Property(e => e.Apellido).HasMaxLength(120);
            entity.Property(e => e.ConcatenaIdentificacionTipo)
                .HasMaxLength(17)
                .IsUnicode(false)
                .HasComputedColumnSql("(([TipoIdentificacion]+'-')+[NumeroIdentificacion])", true);
            entity.Property(e => e.ConcatenaNombresApellidos)
                .HasMaxLength(241)
                .HasComputedColumnSql("(([Nombre]+' ')+[Apellido])", true);
            entity.Property(e => e.Email)
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre).HasMaxLength(120);
            entity.Property(e => e.NumeroIdentificacion)
                .HasMaxLength(13)
                .IsUnicode(false);
            entity.Property(e => e.TipoIdentificacion)
                .HasMaxLength(3)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PbgUsuario>(entity =>
        {
            entity.HasKey(e => e.Identificador)
                .HasName("Pk_Pbg_Usuario")
                .IsClustered(false);

            entity.ToTable("Pbg_Usuario");

            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Pass).HasMaxLength(120);
            entity.Property(e => e.Usuario).HasMaxLength(120);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}